#!/bin/bash
export MAIN_DIR=$PWD
export JAVA=/usr/bin/java  # 使用系統安裝的 Java 21
cd server

mem=$(grep MemTotal /proc/meminfo | sed -e 's/MemTotal:[ ]*//' | sed -e 's/ kB//')
mem=$(($mem/1024/1024))

# 使用 Java 21 啟動伺服器
$JAVA -Xmx${mem}G -Xms${mem}G -jar server.jar nogui
