#!/bin/bash
export MAIN_DIR=$PWD
export JAVA=/usr/bin/java 
cd server

mem=$(grep MemTotal /proc/meminfo | sed -e 's/MemTotal:[ ]*//' | sed -e 's/ kB//')
mem=$(($mem/1024/1024))

$JAVA -Xmx${mem}G -Xms${mem}G -jar server.jar nogui
